# -*- coding: utf-8 -*-
"""Update the text (numbers, claims, cross-references, references) of SPE_数据库_v16.2.docx."""
import os

import docx

DST = r'D:\GitHub_programe\GitHub\SPE_Database\Datasets\4_Writing\SPE_数据库_v16.2.docx'
doc = docx.Document(DST)


def set_text(p, text):
    if not p.runs:
        p.add_run(text)
        return
    p.runs[0].text = text
    for r in p.runs[1:]:
        r.text = ""


def set_par(i, text):
    set_text(doc.paragraphs[i], text)


EDITS = {}

# ------------------------------------------------------------------ Abstract
EDITS[6] = (
    "The self-matching task, also known as self-tagging task, self-assiciative learning task, "
    "is widely used to investigate how self-related information is proccessed. In a typical "
    "self-matching task, participants first associate social labels (e.g., self, friend, and "
    "stranger) with geometric shapes (e.g., circle, triangle, and square) and then finish a "
    "matching task where they are asked to decide whether the shape-label pairings match the "
    "learned associations. Previous studies using this task have found faster and more accurate "
    "responses to self- than other-related pairings, i.e., the self-prioritization effect (SPE). "
    "Following the credibility revolution, a substantial number of these studies openly shared "
    "their data, created great potential for data re-using. However, there lacks of a standardized "
    "framework for sharing trial-level data generated by self-matching task, making it difficult "
    "to integrate existing open datasets. To fill the gap, we developed a three-level framework "
    "for organizing the metadata and trial-level data. We created machine-readable JSON files to "
    "document task implementations, including Physical Environment, Experimental Design, Block "
    "Structure, Trial Structure, and Stimulus Properties. We applied this framework to data "
    "available from 49 studies (89 experiment-level datasets, 4,875 participants, and over 2.1 "
    "million test trials). We demonstrated the value of the standardized open database through "
    "three examples: the effect of baseline conditions on SPE magnitude; the variability of SPE "
    "under nonmatch conditions; and the relationships between task details (duration of presenting "
    "time and number of trials) and SPE magnitude. The three examples show that standardizing "
    "meta-data across studies is what makes such aggregated analyses possible: the SPE was reliably "
    "positive against every baseline but differed reliably only between the baselines with the "
    "largest and the smallest point estimates; the SPE under nonmatching conditions was present but "
    "depended on how self-relevance was operationalized; and the magnitude of the SPE was related "
    "to stimulus presentation duration but not to the number of trials. Our standardized SPE "
    "database provides a valuable resource for the field. Moreover, our standardized framework for "
    "self-matching task is also valuable for developing similar databases for other cognitive tasks."
)

# ------------------------------------------------------------------ Intro
EDITS[13] = (
    "To address these issues, we developed a standardized framework for data organization and "
    "documentation, applied this framework to available open data, and formed the SPE database. "
    "To capture the methodological details systematically, we decomposed the self-matching task "
    "into five components and documented information of each with standardized metadata files. "
    "We then collected all available datasets and manually standardized both behavioral variables "
    "and methodological descriptors to ensure cross-study comparability. In total, data from 49 "
    "studies, comprising 89 experiment-level datasets, were included. The SPE database enables "
    "analyses that would be impossible for small sample size studies. "
)

# ------------------------------------------------------------------ Dataset_inf row semantics
EDITS[21] = (
    "The root folder also contains a master metadata file (\"Dataset_inf.csv\"), which serves as "
    "the primary index for the entire database, and study-specific sub-folders (e.g., "
    "\"Amodeo_2024_CABN\"). Each row in this file represents one experiment-by-participant-group "
    "unit and is uniquely identified by the combination of the study folder (`Folder_Name`), the "
    "experiment identifier (`Exp`), and the participant group (`subj_Group`); the concatenation of "
    "these three fields forms the `ID` column, which is the key across the database. Each column of "
    "\"Dataset_inf.csv\" corresponds to a metadata field of the studies, such as authors, "
    "publication year, journal name (where applicable), Digital Object Identifiers (DOIs), and "
    "sample descriptors. Importantly, the study-specific folder (`Folder_Name`) was included in "
    "\"Dataset_inf.csv\" for clear mapping between studies and their data folders."
)

# ------------------------------------------------------------------ study-level JSON content
EDITS[22] = (
    "The study-specific folder contains a JSON file, e.g., `Amodeo_2024_CABN.json`, and "
    "experiment-specific sub-folders. The JSON file contains study-level information such as the "
    "theoretical background, a summary of the study, its main conclusion, the publication year and "
    "journal (where applicable), the country and city in which the data were collected, and the "
    "Digital Object Identifier. The experiment-specific subfolders correspond to the individual "
    "experiments reported within the the study. However, if a study contains only a single "
    "experiment, the experimental-level data are stored in the study-level folder directly and no "
    "experiment-specific subfolder was created."
)

# ------------------------------------------------------------------ file-naming examples
EDITS[23] = (
    "For those studies reported more than one experiment, each experiment has its own subfolders "
    "(e.g., `Exp1`, `Exp2`). Each experimental-level sub-folder include the following files: a CSV "
    "file for participants' demographic information (e.g., \"Amodeo_2024_CABN_Exp1_subj_info.csv\"), "
    "a JSON file for the experiment design (e.g., \"Amodeo_2024_CABN_Exp1.json\"), a CSV file for "
    "raw trial-level behavioral data file (e.g., \"Amodeo_2024_CABN_Exp1_raw.csv\"), a CSV file for "
    "the minimally preprocessed dataset (i.e., clean data, e.g., "
    "\"Amodeo_2024_CABN_Exp1_Clean.csv\"), and an xlsx file serves as the codebook for the clean "
    "data (e.g., \"Codebook_Amodeo_2024_CABN_Exp1_Clean.xlsx\"). To facilitate efficient data "
    "retrieval and readability, all file names include four pieces of information — last name of "
    "the first author, publication year, journal abbreviation, and experiment identifier. "
    "Additionally, an optional fifth element specifies the content or function of the file (e.g., "
    "\"_subj_info\" means information related to participants, \"_raw\" means unprocessed data from "
    "original studies, \"Codebook_\" marks the codebook of the clean data). Together, these rules "
    "enhance data interoperability and facilitate large-scale secondary analyses."
)

# ------------------------------------------------------------------ typo: Ratchliff -> Ratcliff
EDITS[25] = (
    "\tTo further facilitate cross-study integration of datasets, we developed a framework for "
    "standardizing the implementation of the self-matching task. This framework dissects the task "
    "into five components: Physical Environment, Experimental Design, Block Structure, Trial "
    "Structure, and Stimulus Properties (Figure 2). These five components zoom from the enviroment "
    "in which the experiment was done to the details of stimuli. Also, these details may also play "
    "a role in cognitive proccesses (e.g., Gold & Shadlen, 2007; Ratcliff et al., 2016), and allow "
    "nuanced cross-study analyses. We standardized all these five components of each experiment and "
    "stored the in the experiment-specific json file (e.g., \"Amodeo_2024_CABN_Exp1.json\") whenever "
    "relevant information is available."
)

# ------------------------------------------------------------------ database scale
EDITS[35] = (
    "The Self-Matching Database is hosted on the Open Science Framework (OSF) website (XXX) and "
    "Science Data Bank (XXX). In the current release (September 2026), the database contains 49 "
    "studies, corresponding to 107 experiment-by-participant-group entries (89 experiment-level "
    "data files) and aggregating 4,875 participants across 2,131,108 test trials (See Table 1 for "
    "details)."
)

# ------------------------------------------------------------------ Table 1 note
EDITS[39] = (
    "Note. N = number of participants retained in the minimally preprocessed data of each "
    "experiment-by-participant-group entry; Trials = number of test trials per participant as "
    "documented in the master index; Exp_Implement = laboratory or online administration as "
    "documented in the experiment-level JSON metadata. The diversity of countries, languages, "
    "stimulus modalities, and experimental designs ensures that future re-analyses can address a "
    "broad range of scientific questions—from the robustness and generalisability of the SPE "
    "across cultures and stimulus formats, to the identification of experimental design parameters "
    "that moderate the magnitude of the effect."
)

# ------------------------------------------------------------------ caption Figure 1
EDITS[20] = "Figure 1. Database folder structure."
EDITS[28] = (
    "Figure 2. (a) Standardized implementation framework and five-component decomposition of the "
    "self-matching task; (b) an example of the experiment-specific json file."
)
EDITS[45] = "Figure 3. Standardized codebook of the experimental dataset variables."

# ------------------------------------------------------------------ six identity categories
EDITS[43] = (
    "As we mentioned in the section Folder Structure, data files include both raw trial-level data "
    "files shared from each team (e.g., \"Amodeo_2024_CABN_Exp1_raw.csv\") and minimally "
    "preprocessed data files (e.g., \"Amodeo_2024_CABN_Exp1_Clean.csv\"), both are stored in "
    "experiment-specific subfolders (see Section XXX). The corresponding codebook (e.g., "
    "\"Codebook_Amodeo_2024_CABN_Exp1_Clean.xlsx\") describes each column (see Figure 3). Basic "
    "information such as participant index (Subject), matching condition (Matching; matching or "
    "nonmatching), shape stimulus (Shape), label stimulus (Label), reaction time in milliseconds "
    "(RT_ms) and seconds (RT_sec), and response accuracy (ACC) are included in all experiments. "
    "The identity columns for both shape and label in data files were standardized into six "
    "categories: Self, Close, Acquaintance, Celebrity, Stranger, and NonPerson (Sun et al., 2023). "
    "For clarity, we kept the original identity names (\"Origin_Identity\"), the English-translated "
    "identity names (\"English_Identity\"), and the standardised identity categories "
    "(\"Standardised_Identity\"). The minimally preprocessed data files may also include additional "
    "fields that describe the experimental design, such as block number, trial number within block, "
    "experimental phase or session, specific stimulus features (e.g., face gender, voice accent, "
    "emotional valence), and participant response keys. We expect these minimally preprocessed data "
    "files will be valuable for researchers interested in re-using this database."
)

print('text edits staged:', len(EDITS))
for i, t in EDITS.items():
    set_par(i, t)

doc.save(DST)
print('saved ->', DST)
